server:
  port: 8888


mybatis:
  mapper-locations: classpath*:mybatis/**/*Mapper.XML
  typeAliasesPackage: cn.doublefloat.jdmall.project.**.domain
spring:
  datasource:
    username: jd-mall
    password: 123456
    url: jdbc:mysql://cdb-2tt4kxl0.bj.tencentcdb.com:10151/jd-mall
    driver-class-name: com.mysql.cj.jdbc.Driver